### ISSUE TITLE
Need logging.

### ISSUE THREAD

**Issue by AnatoliyKozlov** [ProxiDoz/shoblabot#3]
Need add normal logging or common print messages to stdout throught print("...").
Not necessacry for all action but minimum for places where catching exceptions.
If decide common print, than need transfer output from stdout to file when run script.

**Comment by anashkinaa** [comment]
Just added logging shit to my shitcode.
You can check it and check log file using /log command.
The issue will be closed after testing and may be some updates.

**Comment by anashkinaa** [comment]
Logging enabled
