### ISSUE TITLE
Need tests

### ISSUE THREAD

**Issue by AnatoliyKozlov** [ProxiDoz/shoblabot#4]
Need basic unit tests coverage.

**Comment by anashkinaa** [comment]
At the moment a lot and over dohuya of tests are performing. Every feature is tested via test bot before adding to prod

**Comment by AnatoliyKozlov** [comment]
I mean need auto tests not ruchnoy proverka na dev okruzhenii

**Comment by ProxiDoz** [comment]
Дак сделай ebaniy rot
